## see reference example for details:
# https://github.com/Ouranosinc/Magpie/blob/master/config/config.yml

providers:
  # definition of Weaver service
  weaver:
    url: http://localhost:4001
    title: Weaver (EMS)
    public: true
    c4i: false
    type: api
    sync_type: api

  # FIXME: remove when https://github.com/Ouranosinc/Magpie/issues/360 implemented, see 'default.env'
  weaver-wps:
    url: http://localhost:4001/wps
    title: Weaver (WPS)
    public: true
    c4i: false
    type: wps
    sync_type: wps

permissions:
  # Entrypoint
  - service: weaver
    permission: read-match
    group: anonymous
    action: create

  # OpenAPI JSON schema
  - service: weaver
    resource: /json
    permission: read
    group: anonymous
    action: create

  # OpenAPI Swagger
  - service: weaver
    resource: /api
    permission: read
    group: anonymous
    action: create

  # Process deploy/listing (builtin/deployed processes)
  - service: weaver
    resource: /processes    # GET is processes listing, POST is deploy: only allow view by anonymous
    permission: read        # under '/processes/...', JSON 'DescribeProcess', POST job submit, GET results, etc.
    group: anonymous
    action: create

  # Providers listing
  - service: weaver
    resource: /providers
    permission: read-match
    group: anonymous
    action: create

  # Provider processes listing
  # (each provider in './components/weaver/config/weaver/wps_processes.yml.template')
  # catalog
  - service: weaver
    resource: /providers/catalog
    permission: read
    group: anonymous
    action: create
  # finch
  - service: weaver
    resource: /providers/finch
    permission: read
    group: anonymous
    action: create
  # flyingpigeon
  - service: weaver
    resource: /providers/flyingpigeon
    permission: read
    group: anonymous
    action: create
  # hummingbird
  - service: weaver
    resource: /providers/hummingbird
    permission: read
    group: anonymous
    action: create
  # malleefowl
  - service: weaver
    resource: /providers/malleefowl
    permission: read
    group: anonymous
    action: create
  # raven
  - service: weaver
    resource: /providers/raven
    permission: read
    group: anonymous
    action: create

  # FIXME: remove when https://github.com/Ouranosinc/Magpie/issues/360 implemented
  # for the moment, align WPS processes to allow public GetCapabilities and DescribeProcess like REST endpoint does
  - service: weaver-wps
    permission: getcapabilities
    group: anonymous
    action: create
  - service: weaver-wps
    permission: describeprocess
    group: anonymous
    action: create
