# label rules used by .github/workflows/label.yml

# label 'ci' all automation-related steps and files
#   Since this repository is in itself an automation process to deploy a server instance,
#   we refer here to CI as the 'meta' configuration files for managing the code and integrations with the repository,
#   not configurations related to the deployment process itself.
ci/operations:
  - .*  # all '.<something>' files
  - .github/**/*
  - docs/Makefile
  - Dockerfile*
  - docker/**/*
  - tests/**/*

ci/deployment:
  - deployment/**/*
  - scripts/**/*
  - templates/**/*
  - vagrant-utils/**/*
  - birdhouse/**/*.include.sh
  - birdhouse/pavics-compose.sh

documentation:
  - "*.rst"
  - "*.example"
  - ".readthedocs.yml"
  - docs/**/*
  - CONTRIBUTING.rst
  - README.rst

component/weaver:
  - birdhouse/**/weaver/**/*

component/cowbird:
  - birdhouse/**/cowbird/**/*

component/magpie:
  - birdhouse/**/magpie/**/*

component/twitcher:
  - birdhouse/**/twitcher/**/*

component/THREDDS:
  - birdhouse/**/thredds/**/*

component/geoserver:
  - birdhouse/**/geoserver/**/*
  - docker/geoserver/**/*

component/jupyterhub:
  - birdhouse/**/jupyterhub/**/*

feature/WPS:
  - birdhouse/**/finch/**/*
  - birdhouse/**/flyingpigeon/**/*
  - birdhouse/**/hummingbird/**/*
  - birdhouse/**/malleefowl/**/*
  - birdhouse/**/raven/**/*
  - birdhouse/**/weaver/**/*
  - birdhouse/**/wps_output-volume/**/*
  - birdhouse/**/*wps*/**/*
