version: '2.1'
services:
  proxy:
    volumes:
      - ./optional-components/canarie-api-full-monitoring/canarie_api_full_monitoring.py:${CANARIE_MONITORING_EXTRA_CONF_DIR}/canarie_api_full_monitoring.py:ro

# vi: tabstop=8 expandtab shiftwidth=2 softtabstop=2
