version: "3.4"
services:
  magpie:
    volumes:
    - ./optional-components/generic_bird/config/proxy/permissions.cfg:${MAGPIE_PERMISSIONS_CONFIG_PATH}/generic_bird-permissions.cfg:ro
    - ./optional-components/generic_bird/config/proxy/providers.cfg:${MAGPIE_PROVIDERS_CONFIG_PATH}/generic_bird-providers.cfg:ro