version: "3.4"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "10"

services:
  raven:
    image: pavics/raven:${RAVEN_VERSION}
    container_name: raven
    environment:
      PYWPS_CFG: /wps.cfg
      # Keep for backward-compat with older RavenWPS.
      GEO_URL: "${RAVEN_GEO_URL}"
      # Forward-compat with newer RavenWPS not yet in this stack.
      RAVEN_GEOSERVER_URL: "${RAVEN_GEO_URL}"
      RAVENPY_GEOSERVER_URL: "${RAVEN_GEO_URL}"
    volumes:
      - ./config/raven/wps.cfg:/wps.cfg
      - /tmp
    restart: always
    logging: *default-logging
