version: "3.4"
services:
  magpie:
    volumes:
      - ./deprecated-components/all-public-access-deprecated/config/ncwms2/permissions.cfg:${MAGPIE_PERMISSIONS_CONFIG_PATH}/all-public-access-ncwms2-permissions.cfg:ro
