version: "3.4"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "10"

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    networks:
      - mongodb
    volumes:
      - ${DATA_PERSIST_ROOT}/mongodb_persist:/data/db
    restart: always
    logging: *default-logging

networks:
  mongodb: {}
