version: '3.4'

services:
  jupyterhub:
    environment:
      WORKSPACE_DIR: ${DATA_PERSIST_ROOT}/${USER_WORKSPACES}
    volumes:
      - "${DATA_PERSIST_ROOT}/${USER_WORKSPACES}:${DATA_PERSIST_ROOT}/${USER_WORKSPACES}"