version: '3.4'

services:
  cowbird:
    environment:
      JUPYTERHUB_USER_DATA_DIR: ${JUPYTERHUB_USER_DATA_DIR}
    volumes:
      - ${JUPYTERHUB_USER_DATA_DIR}:${JUPYTERHUB_USER_DATA_DIR}
  cowbird-worker:
    environment:
      JUPYTERHUB_USER_DATA_DIR: ${JUPYTERHUB_USER_DATA_DIR}
    volumes:
      - ${JUPYTERHUB_USER_DATA_DIR}:${JUPYTERHUB_USER_DATA_DIR}
  jupyterhub:
    environment:
      WORKSPACE_DIR: ${USER_WORKSPACES}
    volumes:
      - "${USER_WORKSPACES}:${USER_WORKSPACES}"
