version: "3.4"
services:
  magpie:
    volumes:
    - ./optional-components/secure-data-proxy/config/magpie/permissions.yml:/opt/local/src/magpie/config/providers/secure-data-proxy.yml:ro
    - ./optional-components/secure-data-proxy/config/magpie/permissions.yml:/opt/local/src/magpie/config/permissions/secure-data-proxy.yml:ro
