version: "3.4"
services:
  magpie:
    volumes:
    - ./components/stac/config/magpie/config.yml:/opt/local/src/magpie/config/permissions/stac.yml:ro
    - ./components/stac/config/magpie/config.yml:/opt/local/src/magpie/config/providers/stac.yml:ro
