version: "3.4"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "10"

services:
  stac:
    container_name: stac
    image: ghcr.io/crim-ca/stac-app:main
    depends_on:
      - stac-db
    # TODO : define creds in env files
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST_READER=stac-db
      - POSTGRES_HOST_WRITER=stac-db
      - POSTGRES_PORT=5432
      - ROUTER_PREFIX=/stac
    logging: *default-logging

  stac-populator:
    container_name: stac-populator
    build:
      context: ./components/stac/populator
      dockerfile: Dockerfile
    environment:
      - STAC_ASSET_GENERATOR_TIMEOUT=15
      - STAC_HOST=http://stac:8000/stac
    volumes:
      - ./components/stac/populator:/populator:ro
    command: >
      bash -c "cd /populator && ./wait-for-it.sh stac:8000 -t 30 && ./populate.sh"
    depends_on:
      - stac

  stac-browser:
    container_name: stac-browser
    image: ghcr.io/crim-ca/stac-browser:docker_image_push
    entrypoint: "/bin/sh -c 'npm run build -- --catalogUrl=https://${PAVICS_FQDN}/stac/ --pathPrefix=/stac-browser/ && serve -s dist -l 8080'"

  stac-db:
    container_name: stac-db
    image: ghcr.io/stac-utils/pgstac:v0.6.10
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
      - PGUSER=username
      - PGPASSWORD=password
      - PGHOST=localhost
      - PGDATABASE=postgis
    volumes:
      - stac-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  # extend proxy with endpoint and config for STAC API access
  proxy:
    volumes:
      - ./components/stac/conf.extra-service.d:/etc/nginx/conf.extra-service.d/stac:ro
    links:
      - stac

  # extend Magpie permissions to grant access to STAC API via secured Twitcher proxy
  magpie:
    volumes:
      # NOTE:
      #   Although file uses the "config.yml" format, it is very important to pass it as independent/duplicate reference
      #   provider/permissions config files. This is because 'MAGPIE_CONFIG_PATH' is not used to allow parsing multiple
      #   config files for each extendable service, using loading of all configuration files found in mount directories.
      - ./components/stac/config/magpie/config.yml:/opt/local/src/magpie/config/permissions/stac.yml:ro
      - ./components/stac/config/magpie/config.yml:/opt/local/src/magpie/config/providers/stac.yml:ro

volumes:
  stac-db:
