version: '2.1'

services:
  scheduler:
    image: pavics/crontab:0.6-rc2
    container_name: scheduler
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./components/scheduler/config.yml:/opt/crontab/config.yml:ro
    environment:
      COMPOSE_DIR: ${PWD}
      JUPYTERHUB_USER_DATA_DIR: ${JUPYTERHUB_USER_DATA_DIR}
    restart: always

# vi: tabstop=8 expandtab shiftwidth=2 softtabstop=2
