version: '2.1'

services:
  # https://github.com/google/cadvisor/blob/master/docs/running.md
  # Collect per container metrics.
  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.36.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    ports:
      - 9999:8080
    devices:
      - /dev/kmsg
    restart: unless-stopped

  # https://github.com/prometheus/node_exporter
  # Collect system-wide metrics.
  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.0.0
    container_name: node-exporter
    volumes:
      - /:/host:ro,rslave
    ports:
      - 9100:9100
    network_mode: "host"
    pid: "host"
    command: --path.rootfs=/host
    restart: unless-stopped

  # https://prometheus.io/docs/prometheus/latest/installation
  # Monitor and store collected metrics.
  prometheus:
    image: prom/prometheus:v2.19.0
    container_name: prometheus
    volumes:
      - ./components/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    restart: unless-stopped

# vi: tabstop=8 expandtab shiftwidth=2 softtabstop=2
