version: '2.1'

services:
  # https://github.com/google/cadvisor/blob/master/docs/running.md
  # Collect per container metrics.
  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.36.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    ports:
      - 9999:8080
    devices:
      - /dev/kmsg
    restart: unless-stopped

# vi: tabstop=8 expandtab shiftwidth=2 softtabstop=2
