version: '2.1'
services:
  emu:
    image: ${EMU_IMAGE}
    container_name: emu
    environment:
      - PYWPS_CFG=/wps.cfg
    ports:
      - "8888:5000"
    volumes:
      - ./optional-components/emu/wps.cfg:/wps.cfg
      - ${EMU_WPS_OUTPUTS_VOL:-wps_outputs}:/data/wpsoutputs
      - /tmp
    restart: always

  magpie:
    volumes:
    - ./optional-components/emu/emu-magpie-permission.cfg:/opt/local/src/magpie/config/permissions/emu-magpie-permission.cfg:ro
    - ./optional-components/emu/emu-magpie-provider.cfg:/opt/local/src/magpie/config/providers/emu-magpie-provider.cfg:ro

  proxy:
    volumes:
    - ./optional-components/emu/emu_canarie_api_monitoring.py:${CANARIE_MONITORING_EXTRA_CONF_DIR}/emu_canarie_api_monitoring.py:ro
